# Name: Mark Waako
# Class: Comp111 Lab A
# Assignment 8 Part 1
l=[]
a=input("What is your first name ?")
b=input("What is your last name ?")
c=int(input("What is your building number ?"))
d=input("What is your street name ?")
e=input("What is your city/town ?")
f=input("What is your province ?")
g=input("What is your postal code ?")
h=int(input("What is your area code ?"))
i=int(input("What is your phone number ?"))
l.append(a)
l.append(b)
l.append(c)
l.append(d)
l.append(e)
l.append(f)
l.append(g)
l.append(h)
l.append(i)
#@l.append(a)
print("The list of information is {}".format(l))

print("Your first name is {}".format(a))
print("Your last name is {}".format(b))
print("Your building number is {}".format(c))
print("Your street name is {}".format(d))
print("Your city/town is {}".format(e))
print("Your your province is {}".format(f))
print("Your postal code is {}".format(g))
print("Your area code is {}".format(h))
print("Your phone number is {}".format(i))
